=== INOC-IT/Granite/web/src/main/resources/templates/document.xsd
<xs:schema
	  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document" type="document"/>
	<xs:complexType name="document">
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="format" type="xs:string"/>
		<xs:attribute name="orientation" type="xs:string"/>
			
		<xs:sequence>			
			<xs:element name="table" minOccurs="0" maxOccurs="unbounded" type="table">
				<xs:complexType name="table">
					<xs:attribute name="columns" type="xs:integer"/>
					<xs:attribute name="widths" type="xs:string"/>
					<xs:attribute name="width" type="xs:float"/>
					<xs:attribute name="align" type="xs:string"/>
					<xs:attribute name="border" type="xs:integer"/>
					<xs:attribute name="borderWidth" type="xs:float"/>
					
					<xs:sequence>						
						<xs:element name="tr" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>			
									<xs:element name="td" minOccurs="0" maxOccurs="unbounded" type="td"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="tr" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>			
									<xs:element name="td" minOccurs="0" maxOccurs="unbounded" type="td"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>	
			<xs:element name="p" minOccurs="0" maxOccurs="unbounded" type="p">
				<xs:complexType name="p">
					<xs:attribute name="align" type="xs:string"/>
					<xs:attribute name="spacingAfter" type="xs:float"/>
					<xs:attribute name="spacingBefore" type="xs:float"/>
					<xs:sequence>						
						<xs:element name="var" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string"/>
							</xs:complexType>
						</xs:element>
						
						<xs:element name="p" minOccurs="0" maxOccurs="unbounded" type="p" />	
						<xs:element name="b" minOccurs="0" maxOccurs="unbounded" type="b" />
						<xs:element name="u" minOccurs="0" maxOccurs="unbounded" type="u" />
						<xs:element name="i" minOccurs="0" maxOccurs="unbounded" type="i" />
						<xs:element name="font" minOccurs="0" maxOccurs="unbounded" type="font" />
				<xs:element name="book" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="author" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<!-- <xs:complexContent>
									<xs:restriction base="xs:anyType"> -->
								<xs:attribute name="name" type="xs:string"/>
									<!-- </xs:restriction>
								</xs:complexContent> -->
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="title" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== INOC-IT/Granite/services/src/test/resources/dossier.xml
<?xml version="1.0"?>
<!-- <fonts>
	<font name="" style="" path="" />
</fonts> -->
<document
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="document.xsd"
	 type="PDF" name="uchcard.pdf" format="A4" orientation="landscape">
	<table columns="1" width="100" align="center" border="15">
		<tr>
            <td><table columns="2" widths="1 8" width="100" align="center" border="0">
                <tr>
                    <td><image src="C:/temp/photo.jpg" /></td>
                    <td align="center">
                        <font size="18" style="bold">Учетная карточка студента</font>

                        <font size="12" style="bold">ГОУ ВПО "<var name="SSU" />"</font>
                    </td>
                </tr>
            </table></td>
		</tr>
	</table>
</document>

=== INOC-IT/Granite/web/src/main/resources/templates/reference-1.xml
<?xml version="1.0"?>
<!-- <fonts>
	<font name="" style="" path="" />
</fonts> -->
<document
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="document.xsd"
	 type="PDF" name="spravka1.pdf" format="A5" orientation="landscape">
	<table widths="4 30 8 24 8 4 6 7 10 25 5 4 5 13 5 7 15" width="100" align="center" border="0">
		<tr>
			<td colspan="6" align="center"><font size="10">
					<p>Федеральное агентство по образованию
						Государственное образовательное
						учреждение
						высшего профессионального образования
						«САРАТОВСКИЙ ГОСУДАРСТВЕННЫЙ
						УНИВЕРСИТЕТ
						имени  Н.Г. Чернышевского»
						410012, г. Саратов, ул. Астраханская, 83
						тел: (845-2) 26-16-96, факс: (845-2)27-85-29
						
						_______________________№_________________
						
						На №______________ от ____________________</p>
				</font></td>
			<td colspan="11">
				<table widths="6 7 10 25 5 4 5 13 5 7 15" width="100" border="0">
					<td colspan="11" align="center"><font size="14"><b>СПРАВКА</b></font>
                    </td>
					
					<td colspan="2" align="center">Дана</td>
					<td colspan="9" align="center" border="2"><var name="Student.lastName_dat" /></td>
					
					<td colspan="2" align="center"></td>
					<td colspan="9" align="center" padding="0"><font size="8">(Ф.И.О.)</font></td>
					
					<td colspan="11" align="center" border="2"><var name="Student.firstName_dat" /> <var name="Student.middleName_dat" /></td>
					
					<td colspan="8" align="center">в том, что он(а) является студентом(кой)</td>
					<td colspan="2" align="center" border="2"><var name="Student.courseNumber" /></td>
					<td align="center">курса</td>
					
					<td colspan="9" align="center" border="2"><var name="Student.division_rad" /></td>
					<td colspan="2" align="center">отделения</td>
					
					<td colspan="9" align="center"><font size="8">(очного, очно-заочного (вечернего), заочного)</font></td>
					<td colspan="2" align="center"></td>
					
					<td colspan="11" align="center" border="2">факультета <var name="FACULTY_SHORTNAME" /></td>
					
					<td colspan="11" align="center"><font size="8">(наименование института, факультета)</font></td>
					
					<td colspan="11" align="center" border="2"><var name="SSU_ONLY_GEN" /> </td>
                    <td colspan="11" align="center" border="2"><var name="SSU_BY" /> </td>
					<td></td>
				</table>
			</td>
			
			<td colspan="3" align="center">Зачислен(а) в СГУ с</td>
			<td colspan="3" align="center" border="2"><var name="Student.startDate" /></td>
			<td colspan="3" align="center">Приказ №</td>
			<td align="center" border="2"><var name="Student.order.number" /></td>
			<td colspan="3" align="center">от</td>
			<td colspan="4" align="center" border="2"><var name="Student.order.date" /></td>
			
			<td colspan="2" align="center">Форма обучения</td>
			<td colspan="5" align="center" border="2"><var name="Student.studyForm" /></td>
			<td colspan="7" align="center">Предполагаемая дата окончания СГУ</td>
			<td colspan="3" align="center" border="2"><var name="Student.endDate" /></td>
			
			<td colspan="2" align="center"></td>
			<td colspan="5" align="center"><font size="8">(бюджетная/ коммерческая)</font></td>
			<td colspan="7" align="center"></td>
			<td colspan="3" align="center"></td>
			
			<td colspan="4" align="center">Справка дана для предоставления</td>
			<td colspan="13" align="center" border="2"> </td>
			
			<td colspan="4" align="center"></td>
			<td colspan="13" align="center"><font size="8">(по месту требования и др.)</font></td>
			
			<td align="center"></td>
			<td colspan="4" align="center" border="2">
				Декан факультета <var name="FACULTY_SHORTNAME" /></td>
			<td align="center"></td>
			<td colspan="5" align="center" border="2"></td>
			<td align="center"></td>
			<td colspan="5" align="center" border="2">
				<var name="FACULTY_DEAN" /></td>
			
		<font size="8">
			<td align="center"></td>
			<td colspan="4" align="center">(директор института, декан)</td>
			<td align="center"></td>
			<td colspan="5" align="center">(подпись, дата)</td>
			<td align="center"></td>
			<td colspan="5" align="center">(инициалы, фамилия)</td>
		</font>
			<td colspan="17" align="center">
				М.П.</td>
		</tr>
	</table>
</document>
